services:
  phpboy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpboy
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
